from tkinter import *
window=Tk()
window.title('Simple Interest Calculator')
window.geometry("380x400")
window.configure(bg='#80E5FF')
def calculate():
    p = float(principle_entry.get())
    r = float(rate_entry.get())
    t = float(time_entry.get())
    si = (p*r*t)/100
    si = round(si, 2)
    name = username.get()
    result_label.destroy()
    msg = si
    output_message=Label(result_frame,text=name+", the simple interest "+str(msg), bg = "#80E5FF", font=("pacifico", 12), width=42)
    output_message.place(x=20,y=40)
    output_message.pack()
app_label=Label(window, text="Simple Interest CALCULATOR", fg = "black", bg = "#80E5FF", font=("pacifico", 20),bd=5)
app_label.place(x=50, y=20)
name_label=Label(window, text="Your Name", fg = "black", bg = "#80E5FF", font=("pacifico", 12),bd=1)
name_label.place(x=20, y=90)
username=Entry(window, text="", bd=2, width=22)
username.place(x=150, y=92)
principle_label=Label(window, text="Enter principle amount (in rupees)", fg = "black", bg = "#80E5FF", font=("pacifico", 12))
principle_label.place(x=20, y=140)
principle_entry=Entry(window, text="", bd=2, width=15)
principle_entry.place(x=260, y=142)
rate_label=Label(window, text="Enter rate of interest (in %)", fg = "black", bg = "#80E5FF", font=("pacifico", 12))
rate_label.place(x=20, y=185)
rate_entry=Entry(window, text="", bd=2, width=15)
rate_entry.place(x=250, y=187)
time_label=Label(window, text="Enter time (in years)", fg = "black", bg = "#80E5FF", font=("pacifico", 12))
time_label.place(x=20, y=230)
time_entry=Entry(window, text="", bd=2, width=15)
time_entry.place(x=250, y=232)
calculate_button=Button(window,text="CALCULATE",fg = "white", bg = "#000066",bd=4,command=calculate)
calculate_button.place(x=20,y=250)
result_frame = LabelFrame(window,text="Result", bg = "white", font=("pacifico", 12))
result_frame.pack(padx=20, pady=20)
result_frame.place(x=20,y=300)
result_label=Label(result_frame,text=" ", bg = "white", font=("pacifico", 12), width=33)
result_label.place(x=20,y=20)
result_label.pack()
window.mainloop()